
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'model.g.dart';

@freezed
class ImageModel with _$ImageModel {
  @HiveType(typeId: 5, adapterName: 'ImageModelAdapter')
  const factory ImageModel({
    @HiveField(0) required final String author,
    @JsonKey(name: "download_url")
    @HiveField(1) required final String url,
    @HiveField(2) required final String id,
    @HiveField(3) required final bool isDownloaded,
  }) = _ImageModel;

  factory ImageModel.fromJson(Map<String, Object?> json)
  => _$ImageModelFromJson(json);
}

/*
{
id: "0",
author: "Alejandro Escamilla",
width: 5000,
height: 3333,
url: "https://unsplash.com/photos/yC-Yzbqy7PY",
download_url: "https://picsum.photos/id/0/5000/3333"
},
* */